set fish_greeting

alias install "sudo pacman -S"
alias update "sudo pacman -Syu"
alias config_fish "nvim ~/.config/fish/config.fish"
alias config_polybar "nvim ~/.config/polybar/config"
alias config_awesome "nvim ~/.config/awesome/rc.lua"
alias remove "sudo pacman -R"
alias config_qtile "nvim ~/.config/qtile/config.py"
alias config_nvim "nvim ~/.config/nvim/init.vim"
alias config_i3 "nvim ~/.config/i3/config"
alias v "nvim"
alias suv "sudo nvim"
alias r "ranger"
alias cpumax "sudo cpupower frequency-set --max"
alias cpumin "sudo cpupower frequency-set --min"
alias cpuinfo "cpupower frequency-info"
alias config_alacritty "nvim ~/.config/alacritty/alacritty.yml"
alias configs "cd ~/.config"
alias config_picom "nvim ~/.config/picom/picom.conf"
alias update_dotfiles "cd ~/dotfiles && git add . && git commit -m"
